### ISSUE TITLE
Selection highlight is black on light theme

### ISSUE THREAD

**Issue by ClonedOne** [kmaasrud/clean-theme-obsidian#3]
Hi, thank you for the theme! I just wanted to mention that the selection highlighting color on light mode is extremely dark -- almost completely black. I think the issue is with line:
```css
::selection, .CodeMirror-selected, .CodeMirror-selectedtext {
    background: var(--text-normal) !important;
```
where `text-normal` ends up being 10,10,10.

I understand light mode is not supported officially, so feel free to disregard this issue. 
Personally, I fixed my css by just defining a new `text-selected` variable for both light and dark themes. In particular 
```css
.theme-light {
  --bg-color: 255, 255, 255;
  --text-color: 10, 10, 10;
  --interactive-accent-rgb: 163, 183, 205;
  --interactive-accent: #a3b7cd;
  --text-selected: #72af8e;
}
.theme-dark {
  --bg-color: 0, 0, 0;
  --text-color: 240, 240, 240;
  --interactive-accent-rgb: 163, 183, 205;
  --interactive-accent: #a3b7cd;
  --text-selected: #7e6cf1;
}
```
However, I don't know if you like those colors. I can send a pr if you'd like.
